name: moto_assistant
description: "Offline Motorcycle Intercom Voice Assistant"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^11.3.1
  path_provider: ^2.1.6
  flutter_tts: ^4.2.5
  url_launcher: ^6.3.2
  shared_preferences: ^2.5.5
  intl: ^0.20.3
  speech_to_text: 7.4.0
  battery_plus: ^6.2.1

dependency_overrides:
  permission_handler_android: ^12.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  image_path: "assets/branding/app_icon.png"
